### ISSUE TITLE
HHAlertEnterModeLeft BUG

### ISSUE THREAD

**Issue by fengarenas** [mrchenhao/HHAlertView#4]
case HHAlertEnterModeLeft:
            {
                //frame.origin.y -= CGRectGetWidth([[UIScreen mainScreen] bounds]);
                interval = 0.5;
            }

HHAlertEnterModeLeft from top
HHAlertLeaveModeLeft also

**Comment by mrchenhao** [comment]
OK。I will see it later，thx

**Comment by mrchenhao** [comment]
fix at pr #5

**Comment by mrchenhao** [comment]
@fengarenas
